Repository Daou-FiveGuys/fiveguys_frontend, pull requests merged in 2024-11, with the labels that each got.

#14 Feature/fg 22 image create renewal
  components/button-command.tsx
  components/chat-list.tsx
  components/chat-panel.tsx
  components/chat.tsx
  components/prompt-form.tsx
  components/stocks/message.tsx
  components/user-text-message.tsx
Labels: bug, ui

#17 [FG-8,9] Add signup and login feature
  app/api/refresh-token/route.ts
  app/login/[provider]/page.tsx
  app/verify/page.tsx
  components/login.tsx
  components/sign-up.tsx
  middleware.ts
  package-lock.json
  package.json
Labels: enhancement

#27 feature/FG-37-address-management
  app/globals.css
  components/address-book.tsx
  components/ui/breadcrumb.tsx
  components/ui/folder.tsx
Labels: enhancement, ui

#30 [FG-21] Add edit image feature
  app/api/refresh-token/route.ts
  app/edit/[imageid]/page.tsx
  app/globals.css
  app/layout.tsx
  app/login/[provider]/page.tsx
  app/providers.tsx
  app/verify/page.tsx
  components/image-confirm-modal.tsx
  components/image-editor.tsx
  components/image-enhance.tsx
  components/image-modal.tsx
  components/image-not-available-modal.tsx
  components/image-processing.tsx
  components/image-save.tsx
  components/login.tsx
  components/modal.tsx
  components/providers.tsx
  components/sign-up.tsx
  middleware.ts
  package-lock.json
  package.json
  redux/provider.tsx
  redux/slices/imageSlice.tsx
  redux/store.ts
  services/apiClient.tsx
  services/authService.tsx
  utils/cookies.tsx
  utils/token.tsx
Labels: enhancement, ui

#59 [debug]: FG-37 newFolder2 group2s init to array
  app/address/service.tsx
Labels: bug

#60 feature/FG-37-address-management
  app/address/address-book.tsx
  app/address/address-list-view.tsx
  app/address/entity.tsx
  app/address/service.tsx
  components/ui/folder.tsx
Labels: bug, enhancement, ui

#62 [bug] : remove "My Page" button in login & signup page
  components/header-link.tsx
Labels: bug

#63 [FG-43] : Design chatbot structure
  app/globals.css
  components/chat-list.tsx
  components/chat-panel.tsx
  components/chat.tsx
  components/chat/faq.tsx
  components/chat/history.tsx
  components/chat/send-message.tsx
  components/chat/usage.tsx
  components/chat/utils/ChatUtils.tsx
  components/chat/utils/MessageItem.tsx
  components/chat/utils/TypingEffect.tsx
  components/image-option-modal.tsx
  components/prompt-form.tsx
  hooks/useChatUtils.ts
  redux/slices/chatSlice.tsx
Labels: enhancement, ui

#64 [FG-45] : Add message history feature
  components/chat-list.tsx
  components/chat.tsx
  components/chat/history/calendar.tsx
  components/chat/history/dummy-data.ts
  components/chat/history/history-panel.tsx
  components/chat/history/history.tsx
  components/chat/history/message-card.tsx
  components/chat/history/message-history.tsx
  components/chat/utils/Calendar.tsx
  components/prompt-form.tsx
  redux/slices/calendarSlice.tsx
  redux/store.ts
Labels: enhancement, ui

#71 [feat] : implement welcome page, improve scrolling animation
  app/globals.css
  app/welcome/page.tsx
  components/animated-button.tsx
  components/chat.tsx
  components/chat/history/HistoryPanel.css
  components/chat/history/calendar.tsx
  components/chat/history/history-panel.tsx
  components/chat/history/message-card-modal.tsx
  components/chat/history/message-card.tsx
  components/chat/history/message-history.tsx
  components/header.tsx
  components/hero-section.tsx
  components/site-header.tsx
  middleware.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement, ui

#73 Feature/create Image to redirect edit page
  components/chat/send-message/create-message.tsx
  components/image-preview-modal.tsx
  next.config.js
Labels: bug, enhancement

#74 Feature/html typing effect
  components/chat-list.tsx
  components/chat/faq.tsx
  components/chat/utils/ChatUtils.tsx
  components/chat/utils/HTMLTypingEffect.tsx
  components/chat/utils/MessageItem.tsx
  package-lock.json
  package.json
  redux/slices/chatSlice.tsx
  services/apiClient.tsx
  tailwind.config.ts
Labels: enhancement, ui

#75 feature/send-message
  components/image-generator.tsx
Labels: bug

#77 [bug-fix] : Fix for repetitive animation triggering bug
  components/chat/utils/ChatUtils.tsx
  components/chat/utils/HTMLTypingEffect.tsx
  components/chat/utils/MessageItem.tsx
Labels: bug

#79 [refactor] : edit tailwind config
  app/edit/page.tsx
  app/globals.css
  app/welcome/page.tsx
  components/animated-button.tsx
  components/chat.tsx
  components/chat/faq.tsx
  components/chat/history/history.tsx
  components/chat/send-message/create-message.tsx
  components/chat/utils/ChatUtils.tsx
  components/header-link.tsx
  components/hero-section.tsx
  components/site-header.tsx
  lib/hooks/use-message-is-empty.tsx
  tailwind.config.ts
Labels: enhancement, ui

#87 [feat] : image compress
  app/address/modal/select-contact-modal.tsx
  app/address/modal/service.tsx
  components/hero-section.tsx
  components/image-editor.tsx
  components/image-method-modal.tsx
  components/image-save.tsx
  redux/slices/imageOptionSlice.tsx
  redux/slices/messageOptionSlice.tsx
  redux/store.ts
  services/apiClient.tsx
Labels: enhancement, ui

#92 [Issue#90] : Fix error when retrieving SMS message history
  components/chat-list.tsx
  components/chat/history/message-card-modal.tsx
  components/chat/history/message-card.tsx
  components/image-editor.tsx
  components/image-save.tsx
  components/login.tsx
Labels: bug

#104 [FG-51] : Add translate text feature
  components/chat-panel.tsx
  components/chat/utils/skip-button.tsx
  components/image-editor.tsx
  components/papago/clipboard-button.tsx
  components/papago/papago-api.ts
  components/papago/papago-pop-up-content.tsx
  components/papago/papago-pop-up.tsx
  components/prompt-form.tsx
Labels: enhancement, ui
